version: "3"

services:
  postgres:
    image: postgres
    container_name: sistemi-postgres
    restart: on-failure:10
    volumes:
      - sistemi-postgres:/var/lib/postgresql/data
    ports:
      - "5431:5432"
    environment:
      POSTGRES_DB: "sistemi"
      POSTGRES_USER: "admin"
      POSTGRES_PASSWORD: "toolz123"
      POSTGRES_HOST_AUTH_METHOD: "trust"
  redis:
    image: redis:6
    container_name: sistemi-redis
    ports:
      - "6380:6379"
volumes:
  sistemi-postgres:
    driver: local
